<header class="header">
    <div class="container">
        <h1 class="logo fl-left">
            <a href="#"><img src="<?php echo $this->serverUrl() . BASEDIR; ?>/res/imgs/logo.png" alt="2 Clics Comunicação"></a>
        </h1>
        <button type="button" class="btn-menu"><i class="icon-menu"></i></button>
        <nav class="menu">
            <ul>
                <li class="menu-item"><a href="#agencia">Agência</a></li>
                <li class="menu-item"><a href="#clientes">Clientes</a></li>
                <li class="menu-item"><a href="#trabalhos">Trabalhos</a></li>
                <li class="menu-item"><a href="#news">News</a></li>
                <li class="menu-item"><a href="#contato">Contato</a></li>
            </ul>
        </nav>
    </div>
</header>
